
CREATE TABLE Doctor(
Id INT PRIMARY KEY IDENTITY(1,1),
FullName NVARCHAR(100) NOT NULL,
Age INT NOT NULL,
Department NVARCHAR(80 ) NOT NULL UNIQUE
);

CREATE TABLE Patients(
Id INT PRIMARY KEY IDENTITY(1,1),
FullName NVARCHAR(60) NOT NULL,
[complaint] NVARCHAR(70) NOT NULL,
DoctorId INT FOREIGN KEY REFERENCES Doctor(Id) NOT NULL

);


CREATE TABLE Hospital(
Id INT PRIMARY KEY IDENTITY(1,1),
Name NVARCHAR(90) NOT NULL,
[Adress] NVARCHAR(30) NOT NULL,
DoctorId INT FOREIGN KEY REFERENCES Doctor(Id) NOT NULL UNIQUE
);

ALTER TABLE Hospital
ADD [DoctorId] INT

UPDATE Hospital
SET [DoctorId]=DoctorId INT FOREIGN KEY REFERENCES Doctor(Id) NOT NULL UNIQUE
WHERE Doctor=DoctorId INT FOREIGN KEY REFERENCES Doctor(Id) NOT NULL UNIQUE
