CREATE DATABASE University

CREATE TABLE Teacher(
Id INT PRIMARY KEY IDENTITY(1,1),
TeacherFullName NVARCHAR(55),
TeacherSalary INT,
);

CREATE TABLE Department(
Id INT PRIMARY KEY IDENTITY(1,1),
DepartmentFullName NVARCHAR(43),
);

CREATE TABLE TeacherDepartment(
Id INT PRIMARY KEY IDENTITY(1,1),
TeacherId INT FOREIGN KEY REFERENCES Teachers(Id), 
DepartmentId  INT FOREIGN KEY REFERENCES Department(Id),
);

CREATE TABLE Subjects(
Id INT PRIMARY KEY IDENTITY(1,1),
SubjectName NVARCHAR(85),
);

CREATE TABLE TeacherAndSubject(
Id INT PRIMARY KEY IDENTITY(1,1),
TeacherId INT FOREIGN KEY REFERENCES Teachers(Id), 
SubjectId INT FOREIGN KEY REFERENCES Subjects(Id), 
);

CREATE TABLE Class(
Id INT PRIMARY KEY IDENTITY(1,1),
ClassNumber INT,
);

CREATE TABLE Student(
Id INT PRIMARY KEY IDENTITY(1,1),
StudentName NVARCHAR(44),
);

CREATE TABLE StudentAndClass(
Id INT PRIMARY KEY IDENTITY(1,1),
StudentId  INT FOREIGN KEY REFERENCES Student(Id),
ClassId INT FOREIGN KEY REFERENCES Class(Id),
);

CREATE TABLE StudentAndSubjects(
Id INT PRIMARY KEY IDENTITY(1,1),
StudentId  INT FOREIGN KEY REFERENCES Student(Id),
SubjectId INT FOREIGN KEY REFERENCES Subjects(Id), 
);

CREATE TABLE Faculty(
Id INT PRIMARY KEY IDENTITY(1,1),
FacultyName NVARCHAR(68),
Auditorium NVARCHAR(87),
);

CREATE TABLE ALLGroup(
Id INT PRIMARY KEY IDENTITY(1,1),
GroupName NVARCHAR(78),
);

CREATE TABLE FacultyAndAllGroup(
Id INT PRIMARY KEY IDENTITY(1,1),
FacultyId INT FOREIGN KEY REFERENCES Faculty(Id),
AllGroupId  INT FOREIGN KEY REFERENCES AllGroup(Id),
);

CREATE TABLE FacultyDepartment(
Id INT PRIMARY KEY IDENTITY(1,1),
FacultyId INT FOREIGN KEY REFERENCES Faculty(Id),
DepartmentId  INT FOREIGN KEY REFERENCES Departments(Id),
);

CREATE TABLE AllGroupAndStudent(
Id INT PRIMARY KEY IDENTITY(1,1),
GroupId INT FOREIGN KEY REFERENCES AllGroup(Id),
StudendtId INT FOREIGN KEY REFERENCES Student(Id),
);

CREATE TABLE Lecture(
Id INT PRIMARY KEY IDENTITY(1,1),
LectureName NVARCHAR(98),
);

CREATE TABLE LectureAndDepatment(
Id INT PRIMARY KEY IDENTITY(1,1),
LectureId INT FOREIGN KEY REFERENCES Lecture(Id),
DepartmentId  INT FOREIGN KEY REFERENCES Departments(Id),
);


CREATE TABLE AllWeeklyprogram(
Id INT PRIMARY KEY IDENTITY(1,1),
DaysOfTheWeek NVARCHAR(97),
LectureId INT FOREIGN KEY REFERENCES Lecture(Id),
SubjectId INT FOREIGN KEY REFERENCES Subjects(Id), 

);






